package cmd

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"html/template"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/spf13/cobra"
)

var (
	reportDir   string
	reportOut   string
	reportTitle string
	reportEmbed bool
)

type manifestRoute struct {
	URL   string  `json:"URL"`
	Name  string  `json:"Name"`
	File  string  `json:"File"`
	Path  string  `json:"Path"`
	Error *string `json:"Error"`
}

type manifest struct {
	Generated string          `json:"Generated"`
	Count     int             `json:"Count"`
	Routes    []manifestRoute `json:"Routes"`
}

type reportData struct {
	Title     string
	Count     int
	Generated string
	Cards     []cardData
}

type cardData struct {
	Name    string
	URL     string
	Src     string
	FullSrc string
}

const reportTmpl = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{.Title}}</title>
<style>
* { box-sizing: border-box; margin: 0; padding: 0; }
body { background: #0f0f0f; color: #e0e0e0; font-family: system-ui, sans-serif; padding: 2rem; }
h1 { font-size: 1.5rem; font-weight: 600; margin-bottom: 0.25rem; }
.meta { color: #666; font-size: 0.85rem; margin-bottom: 2rem; }
.grid { display: grid; grid-template-columns: repeat(3,1fr); gap: 1rem; }
@media (max-width: 1024px) { .grid { grid-template-columns: repeat(2,1fr); } }
@media (max-width: 640px)  { .grid { grid-template-columns: 1fr; } }
.card { background: #1a1a1a; border-radius: 8px; overflow: hidden; }
.card a { display: block; text-decoration: none; color: inherit; }
.card img { width: 100%; height: 200px; object-fit: cover; object-position: top; display: block; }
.card .info { padding: 0.75rem; }
.card .name { font-size: 0.9rem; font-weight: 500; margin-bottom: 0.25rem; }
.card .url  { font-size: 0.75rem; color: #888; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.card .no-img { height: 200px; display: flex; align-items: center; justify-content: center; color: #444; font-size: 0.8rem; }
footer { margin-top: 3rem; color: #333; font-size: 0.8rem; text-align: center; }
</style>
</head>
<body>
<h1>{{.Title}}</h1>
<p class="meta">{{.Count}} screenshot(s) · generated {{.Generated}}</p>
<div class="grid">
{{range .Cards}}
<div class="card">
  <a href="{{.FullSrc}}" target="_blank" rel="noopener">
    {{if .Src}}<img src="{{.Src}}" alt="{{.Name}}" loading="lazy">
    {{else}}<div class="no-img">PDF — click to open</div>{{end}}
    <div class="info">
      <div class="name">{{.Name}}</div>
      {{if .URL}}<div class="url">{{.URL}}</div>{{end}}
    </div>
  </a>
</div>
{{end}}
</div>
<footer>generated by snapr</footer>
</body>
</html>`

var reportCmd = &cobra.Command{
	Use:   "report",
	Short: "Generate an HTML report from captured screenshots",
	Example: `  snapr report
  snapr report --dir screenshots --out screenshots/report.html
  snapr report --title "My Site" --embed=false`,
	RunE: func(cmd *cobra.Command, args []string) error {
		// Collect image files
		entries, err := os.ReadDir(reportDir)
		if err != nil {
			return fmt.Errorf("reading dir %s: %w", reportDir, err)
		}

		var files []string
		for _, e := range entries {
			if e.IsDir() {
				continue
			}
			name := e.Name()
			low := strings.ToLower(name)
			if strings.HasSuffix(low, ".png") || strings.HasSuffix(low, ".jpg") || strings.HasSuffix(low, ".jpeg") {
				files = append(files, name)
			}
		}
		sort.Strings(files)

		// Load manifest if present
		routeByFile := map[string]manifestRoute{}
		mfPath := filepath.Join(reportDir, "manifest.json")
		if data, err := os.ReadFile(mfPath); err == nil {
			var mf manifest
			if json.Unmarshal(data, &mf) == nil {
				for _, r := range mf.Routes {
					routeByFile[r.File] = r
				}
			}
		}

		// Build cards
		cards := make([]cardData, 0, len(files))
		for _, fname := range files {
			base := filepath.Base(fname)
			low := strings.ToLower(base)
			isPNG := strings.HasSuffix(low, ".png")

			var src, fullSrc string
			if reportEmbed {
				imgBytes, err := os.ReadFile(filepath.Join(reportDir, fname))
				if err != nil {
					return fmt.Errorf("reading image %s: %w", fname, err)
				}
				enc := base64.StdEncoding.EncodeToString(imgBytes)
				mime := "image/jpeg"
				if isPNG {
					mime = "image/png"
				}
				src = "data:" + mime + ";base64," + enc
				fullSrc = src
			} else {
				src = base
				fullSrc = base
			}

			name := strings.TrimSuffix(strings.TrimSuffix(strings.TrimSuffix(base, ".jpeg"), ".jpg"), ".png")
			url := ""
			if r, ok := routeByFile[base]; ok {
				if r.Name != "" {
					name = r.Name
				}
				url = r.URL
			}

			cards = append(cards, cardData{
				Name:    name,
				URL:     url,
				Src:     src,
				FullSrc: fullSrc,
			})
		}

		// Ensure output parent dir exists
		outDir := filepath.Dir(reportOut)
		if err := os.MkdirAll(outDir, 0o755); err != nil {
			return fmt.Errorf("creating output dir %s: %w", outDir, err)
		}

		// Render template
		tmpl := template.Must(template.New("report").Parse(reportTmpl))

		f, err := os.Create(reportOut)
		if err != nil {
			return fmt.Errorf("creating report file %s: %w", reportOut, err)
		}
		defer f.Close()

		data := reportData{
			Title:     reportTitle,
			Count:     len(cards),
			Generated: time.Now().Format("2006-01-02 15:04:05"),
			Cards:     cards,
		}

		if err := tmpl.Execute(f, data); err != nil {
			return fmt.Errorf("rendering template: %w", err)
		}

		fmt.Printf("report: %s (%d images)\n", reportOut, len(cards))
		return nil
	},
}

func init() {
	reportCmd.Flags().StringVar(&reportDir, "dir", "screenshots", "directory with screenshots")
	reportCmd.Flags().StringVar(&reportOut, "out", "screenshots/report.html", "output file")
	reportCmd.Flags().StringVar(&reportTitle, "title", "snapr report", "page title")
	reportCmd.Flags().BoolVar(&reportEmbed, "embed", true, "base64-embed images (self-contained HTML)")
	rootCmd.AddCommand(reportCmd)
}
